### ISSUE TITLE
Remove unused i18n templates

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#10]
In the `src/main/i18n/templates` folder, there are a lot of unused keys that should be removed.

Be careful, you can't just delete all keys that don't have a direct usage by searching. For example, there might be a key `death.screen.fizz.title`, but in the code it's referenced using:
```java
String key = "pgm.death.screen." + death.getScreen() + ".title";
```

**Comment by TheMolkaPL** [comment]
There are also tons of messages which are currently hard coded in the source code, but their text is already defined in `strings.properties`, the key is unused.
