### ISSUE TITLE
Implement player freezing

### ISSUE THREAD

**Issue by EudaldC** [Electroid/PGM#135]
Ubiquitous moderation feature. Non-PGM servers mostly don't need it (lobby) and PGM servers absolutely need it. Requires:

- [ ] Command: /f \<username> or /freeze
- [ ] Give ice block to players in observers with perms to pgm.freeze
- [ ] Freeze any players **right** clicked by ice block
- [ ] Don't freeze players with permission pgm.freeze.exempt
- [ ] When a player is frozen they can't move (like in the death screen)
- [ ] Display a title screen or chat message when frozen (depending on version) and play some dragon sound
- [ ] Send to adminchat: `[a] Eudaldca froze Cheater1234`
- [ ] Give freeze perms to pgm.mod
- [ ] Server configurable (enable/disable)

Would require to [port feature back from PGM](https://github.com/StratusNetwork/projectares/tree/master/PGM/src/main/java/tc/oc/pgm/freeze)

**Comment by Electroid** [comment]
I'm okay bringing this back.

**Comment by EudaldC** [comment]
@ThatOneTqnk said he'd work on this

**Comment by Diamyx** [comment]
@ThatOneTqnk any updates on this?

**Comment by ThatOneTqnk** [comment]
Mostly done, expecting to finish in a few days
