### ISSUE TITLE
/map information

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#154]
I'd like to request several things relating to /map

- On stratus we had two useful flags for _/maps,_ one of which was -a where it filtered by map author, and another I forget the letter, but it filtered by gamemode.

- Let's say we've got a 26v26 map. Instead of showing the max players number like it does now, 52, it makes sense to just say "26v26."  Because that's how map limits are thought of, people don't think "oh this is a 52 player map," it's the two team numbers.  This might be extra prevalent on Stratus because of rotation sizes and stuff, but I think it just makes sense everywhere.  And if you're a mod setnexting maps, you want to check the map sizes -- but when you check how many people are online, it's easier to just see "oh we're at a 27v29, probably shouldn't setnext this 26v26" rather than doing a bit of math to see.  I sort of overexplained that, but it just makes sense to me.

- Remove the genre thing, idek what it is or how it works but nobody uses it

**Comment by RuedigerLP** [comment]
it would be cool if u could just do /maps -tags (playername,gamemode,future tags that could be added) future tags for tnt or 4-team or what ever could be useful to find a specific map

**Comment by Xerocoles** [comment]
> it would be cool if u could just do /maps -tags (playername,gamemode,future tags that could be added) future tags for tnt or 4-team or what ever could be useful to find a specific map

That would be cool, but I don't think many people would be aware of it / use it practically ever, and it would require going through every single map's xml, which would be kinda painful

**Comment by RuedigerLP** [comment]
we dont need to add any extra tags now, but it would allow for more tags in the future and also it would be easier to search if u can search for any tags and u dont need to remember the specific flag cus there is only one

**Comment by TheMolkaPL** [comment]
How about something like #hashtags? Most of them would be automatic, but map authors could define their own. Let's say RFV2 would have `#wool` (automatic based wool module) and `#rfw`. You can do `/maps #rfw` to list all race for wool maps.

Other hashtags would be `#tnt` if TNT module is defined, #dte, #dtm, #4team, #ffa, etc.

**Comment by RuedigerLP** [comment]
it should be #ctw not #wool, also would this also inplement searching for map author names?

also id say there should be categories of hashtags that cant be combined like:
- teams: ffa, 1team, 2team, etc.

other hashtags
- gamemodes
- supply-stuff: tnt, diamond, iron, gold etc.

**Comment by Xerocoles** [comment]
I'm pretty sure that hashtags like that would go practically un-used by people in-game, and it's not worth our time.

_However,_ one cool reason for it, would be if we can have a big maps tab on websites with all sorts of filters and stuff, cause people would be more lenient to start exploring map stuff on forums, than in-game.  It would also be much easier to see how to use, and show that it exists.  But don't add it just for a /maps type of command, I would only bother doing the flags I said above (sorting by author & gamemode)

**Comment by TheMolkaPL** [comment]
> it should be `#ctw` not `#wool`

I was thinking about it, but `#dtc` might be more cryptic to users than `#core`. https://github.com/Electroid/PGM/pull/172#discussion_r362303334

> also would this also inplement searching for map author names?

Not now, it's a different feature I would say.

> also id say there should be categories of hashtags that cant be combined like:
>
> teams: `ffa`, `1team`, `2team`, etc.

Sure, I did `#4teams`, `#ffa`, `#teams`. More maptags (let's call them maptags instead of hashtags) can be easily added since they are automatically added to maps depending on their XML modules. All automatic maptags are listed here: https://github.com/TheMolkaPL/PGM-1/blob/maptags/src/main/java/tc/oc/pgm/maptag/StandardMapTags.java

> other hashtags
>
> gamemodes
> supply-stuff: tnt, diamond, iron, gold etc.

Sure, if you have suggestions about additional maptags please tell me. Consider that adding automatic maptags might be difficult. You can't just give maps `#iron` if you are able to craft armor from iron blocks. That's not present in the XML.

Mapmakers can also define custom maptags for each map in XML, for example:

```xml
<maptags>
    <maptag>#helloworld</maptag>
</maptags>
```

> I'm pretty sure that hashtags like that would go practically un-used by people in-game, and it's not worth our time.

It will on the other hand categorize maps in different gamemodes and features they have. Making it simpler to explore.

**Comment by RuedigerLP** [comment]
> Mapmakers can also define custom maptags for each map in XML, for example:

well idk if #diamond will be used but #tnt will be a big one i guess

**Comment by TheMolkaPL** [comment]
There is `#autotnt` when

```xml
<tnt>
    <instantignite>on</instantignite>
</tnt>
```

**Comment by RuedigerLP** [comment]
yea but for maps like ssb and bamboo valley 3, we have to add #tnt manually i guess

**Comment by TheMolkaPL** [comment]
If there is TNT in chests or you craft it on your own, mapmakers should mark their maps `#tnt`, yes. It's impossible to do this automatically.

**Comment by TheMolkaPL** [comment]
Maptags are now merged into master :) f70543a391d5feb17321e11b074db364d051469d

**Comment by TheMolkaPL** [comment]
@Pablete1234 I don't think this issue has been yet resolved.

**Comment by Pablete1234** [comment]
Map tags seem to address a relevant part of this, and there's a PR for author filtering as well. I guess "team counts" are still to-do.

**Comment by TheMolkaPL** [comment]
Searching maps from a specific author can now by done using the `-a` flag in `maps`. 06b86a70ac629d93d269b904221722a1c825afc0
