### ISSUE TITLE
Basic moderation commands

### ISSUE THREAD

**Issue by Pablete1234** [Electroid/PGM#156]
I think to give a better out-of-the-box experience, it is nice that PGM implements some basic moderation commands that all use similar & consistent formatting. 
Moderation should use bukkit's methods and also provide a pgm moderation event for APIs to be able to integrate.
A config value that enables/disables mod commands is also relevant, since if you want to use a completely different moderating system having overriding commands would be an annoyance.

- [x] Ban
- [x] Temp ban
- [x] Kick
- [x] Warn
- [x] Mute
- [x] Freeze - See #135 
- [x] Report
- [x] Staff
- [x] Vanish
 - Hide from tab list
 - Force you on obs (and force you to stay on obs)
 - Make player not visible to any other obs
 - Disable your name being tabbed-in on commands
 - Hide from /staff
 - Don't allow others to /msg to you (unless bypass permission)
 - Don't allow you to type in team or global chat
 - Do allow admin chat & /msg to others with bypass
 - Don't count towards /match observer count
 - Display join/leave messages when you vanish/unvanish

**Comment by Brottweiler** [comment]
Temp ban could be it's own command where it defaults to 7 days, so you don't have to specify a time each time (but you should be able to specify a timespan as well).

**Comment by applenick** [comment]
Just curious, has anyone started working on these recently?
I’d be interested in implementing them, though don’t wanna start if someone has already made progress 😄

**Comment by Brottweiler** [comment]
`/staff` would be nice so you could easily see what mods are on maybe? Unless just checking player list is enough.

**Comment by applenick** [comment]
@Brottweiler Awesome!
I’ve wanted to add a `/staff` command, but I was unsure if anyone would find it useful on say OCC, since there’s only one server. Consider it added to the todo list 👍

**Comment by KingOfSquares** [comment]
Maybe close this? Since it was determined out of scope..

**Comment by Electroid** [comment]
See #326

**Comment by Pablete1234** [comment]
I'm closing as i belive all of this has been implemented into pgm
