### ISSUE TITLE
Fix tab list for 1.7 players

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#16]
`ViaRewind` allows `1.7` players to join the server as a `1.8` player. The `1.7` tab list is quite different, so we want to disable it, only problem is `PGM` has no way of determining if the player is a `1.8` player or a secret `1.7` player "disguised" as a `1.8` player. ~~Ideally, we do not import any new APIs to do this.~~ Any ideas?

**Comment by Electroid** [comment]
Seems solution would be to add `ViaVersion` as an optional dependency, and check at runtime.

**Comment by AustinLMayes** [comment]
The dependency was added, but the check is not in place yet - reopening

**Comment by Electroid** [comment]
Fixed ^
