### ISSUE TITLE
You can defuse TNT while being in the Observers team

### ISSUE THREAD

**Issue by bryanowen7** [Electroid/PGM#160]
Nothing much more to say, to reproduce just place a TNT, change into /obs quickly and defuse it.

**Comment by Pugzy** [comment]
Unable to replicate, tested with @Pablete1234

**Comment by Pablete1234** [comment]
From what we tested, you can only defause tnt from obs if you have the perms, or in-game if you are on the same team as the placer (but you didn't place it yourself)
