### ISSUE TITLE
Team filter stuff

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#164]
So in XML, when you get to something like this:
```
<filter name="only-red">
        <team>red</team>
</filter>
<filter name="only-blue">
        <team>blue</team>
</filter>
```

It won't work if the teams look like this:
```
<teams>
	<team id="red" color="dark purple" max="22" max-overfill="26">Trick</team>
	<team id="blue" color="gold" max="22" max-overfill="26">Treat</team>
</teams>
```

From what I can tell, it's looking at the display name of the team rather than the id.  This usually isn't an issue, because, well, the id is usually the same as the display name.  But as you'll notice in some of these seasonal maps, where people don't bother changing id's to match the new team names, it's an issue.  As of right now, you have to change the team id specified in the filter to match the display name rather than the id.

**Comment by TheMolkaPL** [comment]
Yeah, I see that. I'll fix this today.
