### ISSUE TITLE
Void damage should be cancelled for dead players

### ISSUE THREAD

**Issue by Meeples10** [Electroid/PGM#179]

**Comment by Electroid** [comment]
Is there a little bit of context here?

**Comment by Meeples10** [comment]
If a player dies in the void, they still take void damage, causing them to constantly hear the damage sound.

**Comment by TheMolkaPL** [comment]
Was mentioned in #89 but wasn't fixed actually.

**Comment by Xerocoles** [comment]
Yeah it's really annoying especially cause you basically HAVE to respawn.  If you go afk in the void after dying it's like *DUN DUN DUN DUN DUN DUN*

And if you try to say something in chat it will cut you off while typing at what seems to be random intervals from the damage.

**Comment by Meeples10** [comment]
> And if you try to say something in chat it will cut you off while typing at what seems to be random intervals from the damage.

All inventories are closed when you reach 0 HP, including the chat and pause screen--another reason to cancel the damage.

**Comment by TheMolkaPL** [comment]
Fixed in 44b6f7dc0b25e1f13bd605b7715703a9353b533c 👌
