### ISSUE TITLE
Rage maps show as Blitz in the scoreboard

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#184]
Here's an example on BlockRAGE -- it's assuming the rage maps are blitz I guess, but most aren't.
<img width="165" alt="Screen Shot 2020-01-03 at 2 58 20 PM" src="https://user-images.githubusercontent.com/54342797/71745889-83f35f80-2e39-11ea-971e-58519a9e0c35.png">

**Comment by TheMolkaPL** [comment]
Fixed fe7008c0df8645f4ac2c4a1b414a658eb39fcf98 👌
