### ISSUE TITLE
Dead players have gray name when chatting

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#199]
If you are dead and type in chat, your name is gray. This should not happen. Look in `ChatDispatcher`

**Comment by Xerocoles** [comment]
Somewhat related to this: If you were dead and about to respawn, your name would be dark grey in tab for those couple seconds.

This was actually useful for 3 reasons:

- Sometimes you could tell when people were afk if their name was grey forever

- SUPER useful in KotF, trying to see how many people you have left alive / the other team has left alive while holding flag.

- If you’re tunneling / rushing / anything near the opponent’s base, you can check tab to see when the opponent is dying and respawning near you, which helps with timing.  This is one reason why I have all deaths toggled on, but not everyone does.

**Comment by Pablete1234** [comment]
@Xerocoles I don't think you understood this issue. Players not changing to gray, is a bug that has been fixed. It works now.

This issue is about gray name color affecting chat as well as tab, instead of just tab.

**Comment by Xerocoles** [comment]
@Pablete1234 Ah it wasn't like that last I checked I think, epic 👍
