### ISSUE TITLE
Sounds for Kills / Objectives

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#204]
If we could get that raindrop / droplet sound back when you kill someone / get an objective / win the match that would be epic, I think most people would enjoy having it back (not the droplets / raindrops themselves, just the sound)

**Comment by TheMolkaPL** [comment]
Related: https://github.com/OvercastNetwork/ProjectAres/blob/079d13ce62aee9a85f6871384a53356bd25735a8/Commons/bukkit/src/main/java/tc/oc/commons/bukkit/raindrops/RaindropUtil.java#L136

**Comment by TheMolkaPL** [comment]
I wonder if it's something we should have globally (toggleable in the plugin configuration) or something toggleable using player settings.

**Comment by Xerocoles** [comment]
Idk why it would be something you need toggleable per player, I think it's just something that should be normal

**Comment by Pablete1234** [comment]
Definetly should be a player setting, the server should always do this

**Comment by Xerocoles** [comment]
It really doesn't matter that much, but, why toggleable per player?  You don't want to have tons and tons of random player settings cause it gets confusing, isn't that an unnecessary one?  Why not just unify it?

**Comment by Pablete1234** [comment]
What do you even mean by "unify it" ? The server owner is the one that should decide for all players if sound should play or not? That makes no sense. If you're going to have a toggle, it should be a player setting, otherwise, sound should always play.

**Comment by Xerocoles** [comment]
I just think it’s unnecessary for each player to have so many things to toggle, but if you wanna do it, that’s alright, no big deal
