### ISSUE TITLE
Change SidebarMatchModule to render per-player

### ISSUE THREAD

**Issue by Meeples10** [Electroid/PGM#206]
Sidebars are currently rendered per-`Party`. If they were rendered per-player, player-specific sidebar settings, such as @Pablete1234's [suggestion](https://github.com/Electroid/PGM/issues/157#issuecomment-569939575) for a setting to toggle sidebar messages, could be added.

**Comment by Electroid** [comment]
This would just increase the computation factor for sidebars.. not worth the performance.
