### ISSUE TITLE
Command /maps <pagenumber> always defaults to page 1.

### ISSUE THREAD

**Issue by KingOfSquares** [Electroid/PGM#207]
Title, if you try using /maps it will always show page 1 no matter which number you input as page number.

Worth noting that it gives no error when you type characters or signs(!?#"-< etc.) instead of numbers, which is something the command should reject as it asks for a number.

**Comment by TheMolkaPL** [comment]
The new syntax for the `/maps` command is now `[-a <author>] [-p <page>] [[!]#<maptag>...]`. Which means that if you want to see page 2 you'll type `/maps -p 2`.

**Comment by CoWinkKeyDinkInc** [comment]
@TheMolkaPL thanks, we should make a wiki page or some more detailed documentation for this.

**Comment by KingOfSquares** [comment]
You could also add the syntax in /help maps maybe? Currently that does not display anything.

**Comment by Pablete1234** [comment]
This is not really an isue, i'm going to close the issue in favor of #210
