### ISSUE TITLE
Add an auto-respawn setting

### ISSUE THREAD

**Issue by Meeples10** [Electroid/PGM#208]
This would allow players to respawn without having to punch, which is unreliable in its current state.

**Comment by Electroid** [comment]
Why is it unreliable? That seems like the issue to fix?

**Comment by Meeples10** [comment]
I agree, but this is a good alternative in the meantime. I've also heard players requesting this on Stratus as a way to respawn more quickly.

**Comment by Pablete1234** [comment]
This is an XML feature afaik, it's the map makers who decide if the map auto-respawns players or not. I think it's generally not good practice to do so.

**Comment by Brottweiler** [comment]
>Why is it unreliable? That seems like the issue to fix?

Sometimes when you punch, nothing happens, and I've noticed that the only way for me to respawn in those cases is to punch a block instead of the air.

**Comment by Xerocoles** [comment]
Adding this is as an option isn't the right way to go imo.  This will make afk spawnkilling more of an issue, I think it's stupid that so many maps use auto="true" already.

**Comment by Electroid** [comment]
I commented on #209 for reasoning, going to pass on this feature for now.
