### ISSUE TITLE
Investigate memory growth rate

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#21]
The growth rate is not *too* bad, but clearly there are some dangling objects, as growth is scaling over time and not the number of players online. Ideas @cswhite2000 ?

<img width="461" alt="" src="https://user-images.githubusercontent.com/3238291/67640851-0bf93e00-f8ba-11e9-88c7-6aa48d63cc8e.png">

**Comment by TheMolkaPL** [comment]
Related to https://github.com/Electroid/PGM/issues/58#issuecomment-552654843 I guess.

**Comment by TheMolkaPL** [comment]
Any update on this? Did 792951a84184361ede8cf1c4bf417a42a1a73304 fix the issue?

**Comment by EudaldC** [comment]
looks like it got fixed

![2019-12-17_22-55-08](https://user-images.githubusercontent.com/8332105/71037598-4942b500-2120-11ea-95be-21dd672524b1.png)

**Comment by EudaldC** [comment]
![2019-12-22_11-58-36](https://user-images.githubusercontent.com/8332105/71320903-7097da00-24b2-11ea-9434-912fc6e44e44.png)
still happening it seems

**Comment by Pablete1234** [comment]
I have an idea of something that may cause it:
Maps have contexts, that are loaded but discarded on startup, and kept as nullable. As you play different maps, the maps get the context loaded and saved, but never discarded. This means the more maps you play the more contexts you'll keep in memory, wich can contribute to this overall increase overtime.

**Comment by Electroid** [comment]
No longer an issue.
