### ISSUE TITLE
Commands do not expose help or usage instructions

### ISSUE THREAD

**Issue by Pablete1234** [Electroid/PGM#210]
I'm pretty sure this is an issue with intake, and not specifically PGM, but it's still relevant to have it noted as it heavily affects pgm's commands.

**Comment by TheMolkaPL** [comment]
We should *maybe* migrate to another better supported command library? [EngineHub's Piston](https://github.com/EngineHub/Piston) may be an option. It is already been used by [WorldEdit 7](https://github.com/EngineHub/WorldEdit/releases/tag/7.0.0).

Sadly, it is not currently documented, but it is [being implemented to CommandBook](https://github.com/EngineHub/CommandBook/pull/117).

**Comment by KingOfSquares** [comment]
@applenick  Suggested https://github.com/aikar/commands to me, thoughts? 
They have much better documentation, and seems like more recent activity.

**Comment by KingOfSquares** [comment]
Solved in https://github.com/Electroid/intake/commit/59f112a279b44d1ee28a2f7361a10f75e4d0d6af
