### ISSUE TITLE
No voting book if you connect after the match ended

### ISSUE THREAD

**Issue by TheMolkaPL** [Electroid/PGM#211]
If the match has ended and you just connected to the server, you won't receive the voting book to vote for next map.

**Comment by Pablete1234** [comment]
I was aware of this behaviour when i made it, but i really feel like it's not a relevant missing feature. Map orders are not registered as listeners and they are simplified by the fact they aren't. 

If you join mid-cycle chances are you're not even going to have alot of time to decide, and being greeted with a book in the face is likely not that nice either.

Personally, i don't see this as a bug but rather a missing feature, one that i'd personally rather not add.

**Comment by Brottweiler** [comment]
Non issue.
