### ISSUE TITLE
Give observers night vision

### ISSUE THREAD

**Issue by Meeples10** [Electroid/PGM#220]
This is useful for dark maps.

**Comment by Electroid** [comment]
Really nice idea, any reason we don't just always do it?

**Comment by Pablete1234** [comment]
Night vision heavily changes the experience on many maps. As an example, RFV2 is played at night, the map is dark and has glowstone as lighting. Looks pretty awful with night vision.

I'd add a "spectator options" item-gui that allows you to toggle night vision, spectator mode, and possibly other toggles we can find. I'm not sure these should be actual persistent player settings though, but rather activated when explicity enabled.

In cardinal we had spectator tools menu (diamond on last slot), that we could grab some ideas from, it had options for::
 - Teleport (ender pearl, would show all players on a chest menu)
 - Visibility (ender eye, would toggle observer visibility [persistent])
 - Elytra (elytra, would give/remove elytra [persistent], can't do for obvious reasons)
 - Effects (xp bottle, would open a 1-row chest with:)
   - Speed (1, 1.5, 2, 2.5, 3) (sugar, would change speed [persistent])
   - Night vision (would add/remove night vision from player)
 - Gamemode (creative <-> spectator, when going to creative, triggers unstuck command `/!`)
