### ISSUE TITLE
Fix translatable messages in map XML

### ISSUE THREAD

**Issue by Meeples10** [Electroid/PGM#221]
For example, this message in Desert Sanctuary's XML is not translated:
```xml
<respawn spectate="true">
    <message>
        { translate: "death.respawn.confirmed.waiting.flagDropped" }
    </message>
</respawn>
```

This seems to be the cause of the problem: https://github.com/Electroid/PGM/blob/master/src/main/java/tc/oc/pgm/util/XMLUtils.java#L920-L922
All `BaseComponent`s (including `TranslatableComponent`) are cast to `Component`.

**Comment by Pablete1234** [comment]
Fixed in #222
