### ISSUE TITLE
Flag respawn messages don't reset color

### ISSUE THREAD

**Issue by Pablete1234** [Electroid/PGM#226]
![image](https://user-images.githubusercontent.com/11789291/72217461-41630e80-352e-11ea-8f2a-35c94b5eb7f8.png)
The messages should reset to  white after **Blue Flag**

**Comment by Pablete1234** [comment]
It happens on OCC on my 1.15.1 client. Maybe text components are handled differently?

**Comment by KingOfSquares** [comment]
![2020-01-16_14 37 21](https://user-images.githubusercontent.com/19822231/72532571-fcafde00-3873-11ea-94d1-a2b9859f1752.png)
Tested on OCC now on 1.8.9, so it has to be a version thing(Alternatively a ViaVersion conversion thing?). I cant get my multi version server to work so i cant test which version it breaks on.

**Comment by AustinLMayes** [comment]
@Pablete1234 Do drop messages have the same issue? If so then its an issue with translations with a single argument.

**Comment by AustinLMayes** [comment]
Wait never mind, looked at your original screenshot again. Quite strange since the seconds formatting doesn't flow over to the text after. Could you toString the rendered component?

**Comment by Pablete1234** [comment]
I have not done any further testing personally, all i know is on my 1.15.1 client it displays like that. I assume it's being rendered as translatable component and not using a color reset after the flag, and maybe it's using extra components where 1.8 clients may reset from one extra to the next and 1.15 doesn't

**Comment by KingOfSquares** [comment]
Seems like all the strings from https://github.com/Electroid/PGM/blob/master/src/main/java/tc/oc/pgm/flag/state/Respawning.java uses the getColoredName() method, while the other flag strings uses getComponentName() ?

Might be some reason for that, i'm not quite familiar with all the code yet.

And Austin, the seconds formatting does probably not flow over because the coloring is done by a different method?

**Comment by Pablete1234** [comment]
`getColoredName` returns colored string then wraps on a component: `{"text":"§9BlueFlag"}`
`getComponentName` returns name with color on a component: `{"text": "Blue Flag", "color":"blue"}``

**Comment by Pablete1234** [comment]
Fixed by #240

**Comment by KingOfSquares** [comment]
The merge went kinda bad, but i think its done now. So this issue should be closed.
@Pablete1234
