### ISSUE TITLE
Kill streak filter is broken

### ISSUE THREAD

**Issue by CrazyisCreeps** [Electroid/PGM#233]
Not sure if there's already an issue for this, but kill rewards that are given through a kill streak aren't given out to players.
![Capture](https://user-images.githubusercontent.com/7937351/72384922-656c4e80-36ec-11ea-9246-41dbabbe6669.PNG)

**Comment by Pablete1234** [comment]
I'm pretty sure this was because of the kill-streak filter not working properly on this PGM version, not certain tho

**Comment by Pablete1234** [comment]
Fixed in d56751a
