### ISSUE TITLE
Add the command /nick

### ISSUE THREAD

**Issue by KingOfSquares** [Electroid/PGM#251]
A command very useful for:
-Internet famous people
-Mods who are trying to catch somebody toggle a hack
-People sick of their own name.

/nick would ideally be able to have these features:

- Change a players name
     - In the tablist
     - Over the players head
     - In chat

- Display the new nick for all other players except the player having the nick and everyone having
   the permission to see through nicks (Like Mods/Admins/Other Internet famous?) 
      - The nick should be displayed in cursive and the real name should be displayed next to it 
         with a line through. ( If i remember correctly from OCN )

- Change the nicked players skin from other players perspective + make it random which skin it 
   gets

- Make it so the nick applies either on next connect or instantly ( with -i )

- /nick clear should be able to clear the nickname of the player ( Also with optional -i )

- People with permission should be able to set other players nicks or clear them.

- Maybe: 
     - Make /nick list show a list of online nicked players
     - Make /nick show <player> if a player is nicked. ( Pointless if it shows in tab? )

This is obviously quite a lot of features, and it's possible to add parts of this over time. But this hopefully displays of features the complete commands should have.

**Comment by Electroid** [comment]
Not going to bring `/nick` back, it totally overcomplicated PGM and it's not worth supporting. If servers want nickname support, it's better to run PGM in offline mode and use a Bungee/Velocity that supports changing usernames.
