### ISSUE TITLE
Enemy objective competion no sound

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#253]
Whenever an enemy makes an objective u dont hear no sound, but while ur team does you do hear it.

**Comment by TheMolkaPL** [comment]
I don't really understand.

If an enemy completes an objective you don't hear the sound of the completion? I can't reproduce it, I always hear it.

**Comment by Meeples10** [comment]
Is there a specific map that you experience this on?

**Comment by VladyslavLukyanenko** [comment]
It was on Golden Drought Mini, i experienced this on more than a particular map

**Comment by VladyslavLukyanenko** [comment]
Hostile creatures sounds where disabled. Invalid
