### ISSUE TITLE
Maptag for maps that are in the map-pool

### ISSUE THREAD

**Issue by RuedigerLP** [Electroid/PGM#255]
i think it would be nice if a map had a maptag that said if it was in the rotation/mappool, depending on what method is used it could be #rotation or #map-pool.

also i think it would be nice if when u hover over a maptag in /map x it would show a text that describes the maptag, more closely.

also i think a /maptags command that lists all maptags on the server could also be useful, so u know what tags u can search for

**Comment by TheMolkaPL** [comment]
If you type `/maps #` tab completer will suggest you all possible maptags.

**Comment by Pablete1234** [comment]
This seems like a weird mixure of things. Map tags are about the map itself not about it's state on the server (if it's part of a map-pool or not), i wouldn't use map tags for it. 

We could have /map list the pool(s) the map is in, but not via map-tags.
For searching tags, as molka said, if you use `/maps #` it will tab-complete them in.

I'll close this in favor of #257
