### ISSUE TITLE
CTF drop on water unexpected behaviour

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#256]
Whenever u get killed with the flag in water it finds the nearest block and places it there (or thats what i think) doesnt generate ice
Map: Palace CTF

**Comment by Pablete1234** [comment]
@VladyslavLukyanenko PGM has never found "the nearest block", it was always a past-blocks thing. It keeps a history of locations the player was on, and it finds the first valid one. It can happen (on weird cases) that there's no valid spot in all of the saved ones, and the flag directly goes back to respawning state.

**Comment by VladyslavLukyanenko** [comment]
I remember it made ice on water on some maps

**Comment by Pablete1234** [comment]
@VladyslavLukyanenko yes, if your location is one block above water, the water is converted to ice and the flag is placed ontop.

**Comment by VladyslavLukyanenko** [comment]
This might get closed, cause im not sure i was a block above the water
