### ISSUE TITLE
Quotes don't work in @Text command arguments

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#259]
In team chat, `and then he said "sup bro"` would work totally fine, but if you said that in global chat, it would appear as `and then he said sup bro`

**Comment by TheMolkaPL** [comment]
Do you use commands for both global and team chats?

**Comment by Meeples10** [comment]
>Do you use commands for both global and team chats?

@TheMolkaPL this only happens when using the commands. The problem is caused by Intake.

**Comment by Meeples10** [comment]
This is the cause of the problem:
https://github.com/Electroid/intake/blob/5967b510da00ea93d315140714165447f720bd39/core/src/main/java/app/ashcon/intake/argument/CommandContext.java#L108-L140

**Comment by Pablete1234** [comment]
Closed in favor of Electroid/intake#20
