### ISSUE TITLE
Whenever your dead and match ends your nick is gray in tab

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#267]
Whenever your dead and match ends your nick is gray in tab

**Comment by TheMolkaPL** [comment]
If you were dead when the match ended you are still dead after it. After the match ended everything on the server should freeze to the state when it ended.

**Comment by VladyslavLukyanenko** [comment]
Well you get removed from the horse seat and get the items, so i think you should get the gray nick removed

**Comment by Pablete1234** [comment]
The match ended and you're still dead. The fact that you transition to the observing state (like everyone else in the match) doesn't mean you go back to alive.
