### ISSUE TITLE
Tell players that premiums get double map votes

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#269]
A vote from a donor is 2 instead of 1

**Comment by TheMolkaPL** [comment]
I don't understand. What vote?

**Comment by Meeples10** [comment]
Is this a bug or a suggestion? Map votes?

**Comment by Electroid** [comment]
This is a feature, maybe PGM should make it more clear?

**Comment by VladyslavLukyanenko** [comment]
suggestion yeah map votes

**Comment by Pablete1234** [comment]
Ugh... what?

I don't think PGM's job to tell people what the configuration of each server allows them to do.

If a server gives the premium permission for their votes to count twice, make it known in the donation page, or on tips, but pgm isn't the one to handle it.

**Comment by Electroid** [comment]
Yea but having a reminder is helpful? We remind players they need premium to pick a team.

**Comment by Pablete1234** [comment]
We do becaise they're trying to use a command thry have no permission for (`/join` when match is full, or `/join team`), or have toggled the picker to always and tried to join a specific team.

Here all players can vore, both with and without the permission. There's no "error" to be handled or action to be prevented that needs to be explained to the user

**Comment by AhRoon** [comment]
Also, that feature is against of Minecraft's EULA.
So there is no possibility that feature to be added.

**Comment by Brottweiler** [comment]
@AhRoon Could you cite the part of the EULA this feature would be breaking?

**Comment by Pablete1234** [comment]
@AhRoon i very much doubt that is against the EULA. Everyone gets to play the same map, that some people's opinion matter more than others isn't against the EULA

**Comment by Meeples10** [comment]
See here, section "SERVERS AND HOSTING": https://account.mojang.com/terms#commercial

Particularly:
```
- [you may] ask for donations (as opposed to direct charges) IF you do not offer the individual donor something in exchange that only he or she can use. You may offer server wide rewards if donation goals are achieved though.
- [you may] sell cosmetic items, except for “Capes”, IF the item sold does not give a user an unfair gameplay advantage over anyone else on the server - i.e there can be no “pay to win”.
```

**Comment by AhRoon** [comment]
> @AhRoon Could you cite the relevant part of the EULA?



> @AhRoon i very much doubt that is against the EULA. Everyone gets to play the same map, that some people's opinion matter more than others isn't against the EULA



> @AhRoon See here, section "SERVERS AND HOSTING": https://account.mojang.com/terms#commercial
> 
> Particularly:
> 
> ```
> Therefore, if you comply with and follow the Brand and Asset Usage Guidelines and Naming Guidelines above YOU MAY:
> ...
> - ask for donations (as opposed to direct charges) IF you do not offer the individual donor something in exchange that only he or she can use. You may offer server wide rewards if donation goals are achieved though.
> - sell cosmetic items, except for “Capes”, IF the item sold does not give a user an unfair gameplay advantage over anyone else on the server - i.e there can be no “pay to win”.
> ...
> ```

ONE MAJOR RULE

The one major rule is that you must not distribute anything we've made unless we specifically agree to it. By "distribute anything we've made" what we mean is:

give copies of our Game to anyone else;
make commercial use of anything we've made;
try to make money from anything we've made; or
**let other people get access to anything we've made in a way that is unfair or unreasonable**;
unless we specifically agree to it. And so that we are crystal clear, "the Game" or "what we have made" includes, but is not limited to, the client or the server software for our Game and includes Minecraft Pocket Edition on all platforms. It also includes updates, patches, downloadable content, add-ons, or modified versions of a Game, part of those things, or anything else we've made.

Otherwise we are quite relaxed about what you do - in fact we really encourage you to do cool stuff - but just don't do those things that we say you can't.

**Comment by AhRoon** [comment]
Also, about Team Selection and Vote Double, it is against a EULA. Because it gains unfair advantage than normal users(Who doesn't have premium).

**Comment by Meeples10** [comment]
@AhRoon isn't that in regard to piracy? Unfairly/unreasonably distributing the game?

**Comment by AhRoon** [comment]
> @AhRoon isn't that in regard to piracy? Unfairly/unreasonably distributing the game?

It includes Minecraft Server as well.

**Comment by Meeples10** [comment]
@AhRoon Perhaps this conversation could be moved to Discord?

**Comment by AhRoon** [comment]
> @AhRoon Perhaps this conversation could be moved to Discord?

No sorry.

**Comment by Brottweiler** [comment]
That's a stretch and I don't think PGM breaks the Eula in any way.

**Comment by Pablete1234** [comment]
I still don't get what part of the eula we're breaking according to you.

There are several posts by mojang on the topic, as well as the TOS he already linked:
<https://www.mojang.com/2014/06/lets-talk-server-monetisation/>
<https://www.mojang.com/2014/06/lets-talk-server-monetisation-the-follow-up-qa/>
And even more in:
<https://help.minecraft.net/hc/en-us/articles/360034753932-Minecraft-Commercial-Use>


You mention: 
> Also, about Team Selection and Vote Double, it is against a EULA. Because it gains unfair advantage than normal users(Who doesn't have premium).

But that is not part of the gameplay of the server.
One of the specific questions in the follow-up Q&A is:
> **Can I give paying users priority access to my server?**
> Yes, but you cannot restrict gameplay elements to specific users.

Joining full teams or picking the team, is priority joining. Voting can fall on the same style of non-gameplay features given to people with the premium permission.

Once in-game, there are no gameplay restrictions depending on if you paid or not.

If you're able to point out to a specific part of the eula that explicitly prohibits such treatment, point me to it please.

**Comment by KingOfSquares** [comment]
Maybe close this? Looks like discussion is done.

**Comment by Brottweiler** [comment]
Yeah I think if a server want to make it clear premium gives 2x votes, it can do that on the page where you pay for the perks.
