### ISSUE TITLE
Add Rotations

### ISSUE THREAD

**Issue by sharkskill** [Electroid/PGM#27]
It would be good to have rotations or even dynamic rotations based on the player size.

**Comment by Electroid** [comment]
Previously, rotations were defined in text files, I think it just makes sense to put them in the `config.yml`. See `MatchManager#getNextMap` for the current random set next logic.

**Comment by Pugzy** [comment]
The Stratus improvements with dynamic rotations and shuffle functionality are impressive and would be a shame to overlook. An example configuration can be found [here](https://github.com/StratusNetwork/data/tree/master/rotations/beta).

This could work like the `maps` folder having a `rotations` one alongside containing `.yml` files similar to Stratus which include map names and restrictions.

**Comment by Pablete1234** [comment]
Added in #114
