### ISSUE TITLE
Customizable MoTD

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#28]
MoTD should be customizable so you can not only choose the colors you prefer, but also the format, and for example be able to add a newline.

https://github.com/Electroid/PGM/blob/master/src/main/java/tc/oc/pgm/listeners/PGMListener.java#L44

**Comment by Electroid** [comment]
Maybe we check if the `server.properties` motd has a template, and try to fill it in?

`motd=The current map is ${pgm.map}!`

I think `MessageFormat` supports named parameters.
