### ISSUE TITLE
Dangers of Becoming a Monolith

### ISSUE THREAD

**Issue by AustinLMayes** [Electroid/PGM#280]
## The Problem

As the amount of contributions/contributors has grown, and as the amount of ideas have been suggested/implanted, the main project has grown far past a game management system. With upcoming features such as a discord integration, AFK kicker, and various moderation utilities, the project will grow even more. While the "easy to set up" and "out of the box" mindsets behind this project are good ones (and understandable coming from the hell it was to set up all of the OCN infrastructure), I feel that they might be creeping up to a cost on maintainability and extendability. 

## Possible Solutions 
- Do nothing and let it grow, keeping everything in one place
- Split into a multi-module project with core PGM as base which moves common things together but keeps core functionality in the main plugin
- Split into a multi-module project with something else as a base (like a Commons) and group different parts of functionality into different sub-modules

This is more of a long-form discussion thread where I suggest we all contribute some ideas and come to a consensus where the project should move forward.

**Comment by Electroid** [comment]
One of the first steps I want to do is move `tc.oc.pgm.api` into a separate module. However, there are still a few interfaces that reference `tc.oc.pgm` classes (`MapFactory` for example).

I'm also thinking of moving things like moderation stuff and discord into separate modules. Somewhat like an "official" extension to PGM that can be enabled optionally.

**Comment by AustinLMayes** [comment]
We could take the Bungee approach where everything code-wise in split but is all combined together into one "bootstrap" jar for the end user, keeping the easy set up approach but also making the code more maintainable.

**Comment by botinator** [comment]
I agree with the API package module. I wouldn't create any other modules at this point. The code base is still receiving heavy refactors (see: beta branch). It's likely it'll receive more significant refactors in the future. I don't see an immediate benefit to doing this. However, I do see some negative impacts to doing this prematurely (more overhead, some features harder to implement, over-abstraction).

**Comment by KingOfSquares** [comment]
Maybe close this in favour of #326 ? :)
