### ISSUE TITLE
Currently playing doesnt show the authors of the map 

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#281]
https://i.badlion.net/LgmobAMxn9ECzdNUfxA6gR.png

**Comment by Meeples10** [comment]
Is it supposed to? https://github.com/Electroid/PGM/blob/master/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java#L138-L146

**Comment by VladyslavLukyanenko** [comment]
@Meeples10 It was on OCN like that, Electroid probably removid on this commit: https://github.com/Electroid/PGM/commit/529ab16cbbd7f283092460ebe748fee8b23d14a6
