### ISSUE TITLE
Wrong world type (dark sky)

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#285]
I noticed on the PGM Beta all maps seems to be considered of normal world type instead of superflat, so it ignores what the `level.dat` say (some maps *are* normal world type in `level.dat`, but most are superflat).

You can tell because going below y:64 renders the sky black/dark.

## Stable branch
![2020-02-01_18 44 53](https://user-images.githubusercontent.com/1613137/73596587-94bfef80-4523-11ea-8527-a00467b7fd43.png)

## Beta branch
![2020-02-01_18 45 10](https://user-images.githubusercontent.com/1613137/73596589-9e495780-4523-11ea-8c86-fd2f0152c3ad.png)

**Comment by Brottweiler** [comment]
Seems to be fixed on latest stable.

**Comment by Brottweiler** [comment]
Maybe not.. thought OCC was running latest commit but it wasn't.

**Comment by KingOfSquares** [comment]
Ok so i found the bug, unsure of how to implement a fix.

Whenever a `WorldCreator` is constructed with the constructor `WorldCreator(String name)` [https://github.com/Electroid/PGM/blob/771b73913d0bb11eecaca1e6889fd3b6d00a8c2b/core/src/main/java/tc/oc/pgm/match/MatchFactoryImpl.java#L261](here) it will **always** default the WorldType to `DEFAULT`. And the `createWorld` method sets the `WorldType` based on which type the WorldCreator has, and does not in any place (That i can see) look at the level.dat file

Do i need to Override the `CraftServer#createWorld` and make it read level.dat to set the WorldType? How do i even read NBT in Java..

**Comment by KingOfSquares** [comment]
Nevermind, i can just do `WorldCreator#type(WorldType)` to set the type, but i still need to read the level.dat first. Any ideas?

**Comment by Pablete1234** [comment]
It used to work correctly, so, what changed? What different bukkit world creation API is in use for this to be different?
