### ISSUE TITLE
Clicking Team Selector, wears the helmet

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#286]
https://i.gyazo.com/44f8fe6018503fc670d8457f1cfb4d54.mp4

**Comment by TheMolkaPL** [comment]
I wouldn't say that this is a bug. This is a helnet and observers aren't prevented to interact with their inventories. Instead, we should maybe completly cancel all inventory interactions?

**Comment by EudaldC** [comment]
I don't think all inventory interactions should be cancelled. I would personally only cancel that specific interaction with leather helmets only, if it's possible.

**Comment by Pablete1234** [comment]
I do consider this a bug, when interacting with the helmet the event should be cancelled and the menu opened. Inventory interactions in general, shouldn't be blocked
