### ISSUE TITLE
Match stats

### ISSUE THREAD

**Issue by KingOfSquares** [Electroid/PGM#337]
Hello, right now i am almost done making the following features(These are all not stored longer then a Match at a time):

A tracker for each MatchPlayers:
-Kills
-Killstreak(And highest killstreak)
-Deaths
That displays over the hotbars of both the Victim and the Killer on a MatchPlayerDeathEvent(Also making a command to view these stats)

An announcement at the end of each Match that displays the top stats this game, right now:
-Kills
-Highest Killstreak
-Deaths

Also planning to track some more interesting stats for the end announcement like blocks broken, longest bowshot, highest amount of suicides etc.( If some condition is completed)

I was wondering if this is going in the community module? Is any of these features not suitable for PGM? Any more suggestions to add while i'm doing this? Thanks for all feedback.
(And sorry but i'm hopefully the last person to use Components, and not net.kyori)

**Comment by Brottweiler** [comment]
I'm wondering if, even if the stats are temporary, would the addition of total blocks broken for example be large to store, especially if the game is long?

And total suicides might not be great because people might just want to jump off the map repeatedly, which is very bad in TDMs.

**Comment by KingOfSquares** [comment]
> I'm wondering if, even if the stats are temporary, would the addition of total blocks broken for example be large to store, especially if the game is long?
> 
> And total suicides might not be great because people might just want to jump off the map repeatedly, which is very bad in TDMs.

Good points, i was also wondering about the tracking of blocks broken. And about suicides, good thinking, will not track that.

**Comment by KingOfSquares** [comment]
See #338
