### ISSUE TITLE
Missing xml conditional tags

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#34]
```java
/sunrise_over_paradise/map.xml - 'team' attribute of 'spawn' element: no teams defined
/fortress_battles/map.xml - 'team' attribute of 'spawn' element: no teams defined
```

~~The only thing I can figure out is that Sunrise uses this~~
```xml
<cylinder base="0,3,80" radius="1" height="0"/>
```

~~and Fortress Battles uses this~~
```xml
<point>1249,27,519</point>
```
~~But Fortress Battles also uses "cylinder base" for obs spawn so maybe related. Other maps uses a cuboid.~~

**See below**

**Comment by Electroid** [comment]
Conditionals were removed from 1.8. They created complication for XML parsing, were seldomly used, and not really implemented the proper way.
