### ISSUE TITLE
weird large chest 

### ISSUE THREAD

**Issue by ChemistryX** [Electroid/PGM#35]
![2019-10-28_23 18 03](https://user-images.githubusercontent.com/10433434/67686091-8371bf00-f9d9-11e9-9695-39b646a21565.png)
![2019-10-28_23 18 05](https://user-images.githubusercontent.com/10433434/67686104-879ddc80-f9d9-11e9-896f-5194d9e23fe2.png)

large chest looks weird in 1.13 client. maybe issue with viaversion or something?

**Comment by Brottweiler** [comment]
```config
# Enable serverside block-connections for 1.13+ clients
serverside-blockconnections: false
```
Set to `true` to fix chest connections.

**Comment by Pablete1234** [comment]
I'm closing the issue, as it's not related to PGM but rather via version, and a setting to fix it was already provided
