### ISSUE TITLE
Allow Destroyables to be shared/not a have a specific owner

### ISSUE THREAD

**Issue by qlados** [Electroid/PGM#362]
As of now, every destroyable needs a specific owner being a team. That is why I propose that the shared attribute that currently already exists for flags should also be usable for destroyables. 

The main purpose is that when shared/no owner specified, the destroyable is not listed on the scoreboard under every team's objectives, but rather independently, preventing scoreboard clustering for 4-team DTM maps or similar.

**Comment by qlados** [comment]
This could also be solved by adding an `independent` attribute or similar that just does not show it for a specific team on the scoreboard.

**Comment by rafibaum** [comment]
Going to close this in favour of #436 which is broader.
