### ISSUE TITLE
Killrewards for assists

### ISSUE THREAD

**Issue by RuedigerLP** [Electroid/PGM#363]
Killrewards for assists, especially useful if your kill gets cleaned and u can't regenerate cus of this, maybe it could be a config setting where the percentage of needed damage to count as an assist is determined, or as an assist filter where the needed damage is determined.

**Comment by Electroid** [comment]
The issue is we don't have a good way of tracking assists right now.

**Comment by Electroid** [comment]
Going to close for now, kill assists are long away, and we not even implement them.
