### ISSUE TITLE
Scoreboard not showing opponent's wool-touches at first

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#392]
So basically when the match ends, (this was on a 45min timelimit if that means anything) the other team's wool-touch icon won't show up for like 15 seconds or so.  I think these screenshots show it pretty well.

![2020-04-04_00 16 59](https://user-images.githubusercontent.com/54342797/78418535-06dbb000-760b-11ea-980b-9983284efa4f.png)

![2020-04-04_00 18 02](https://user-images.githubusercontent.com/54342797/78418537-0ba06400-760b-11ea-924d-a314ea4cf240.png)

**Comment by EricZeiberg** [comment]
It seems like if an objectives based match ends via timelimit, the other team's touched objectives are not shown to everyone.
