### ISSUE TITLE
MoTD doesn't parse newline properly, and missing §

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#41]
Adding `\n` which should add a newline in the motd doesn't seem to do anything.

Also it seems that `{state.color}` doesn't include the `§`. Not sure if this is intentional, but if it is, the `§` needs to be added to the config (`§{state.color}`) because it's "broken" by default.

![image](https://user-images.githubusercontent.com/1613137/67881923-b2a34000-fb41-11e9-801a-c294ff59d7ee.png)

**Comment by Brottweiler** [comment]
@AustinLMayes I just noticed that, when starting the server, it deletes the `'` from the config. Using `"` works fine!

**Comment by AustinLMayes** [comment]
Yea YML can be annoying like that, glad that fixed it!

#42 Fixes the color issue.
