### ISSUE TITLE
Victory Conditions are checked incorrectly

### ISSUE THREAD

**Issue by Pugzy** [Electroid/PGM#410]
The correct winner of a match can sometimes be incorrectly decided and announced. This can be seen on attack/defend matches like Boom Box where a time limit and team victory condition is set (Defenders win if the match countdown ends). The win will be awarded to the Attackers no matter the completion percentage or time limit. 

After some debugging of the issue there appear to be two issues at play here.

**Issue 1**: The winner is calculated after the countdowns have been removed

The order of the checks [in this bit of code](https://github.com/Electroid/PGM/blob/master/core/src/main/java/tc/oc/pgm/match/MatchImpl.java#L202-L207) was changed after the recent refactor. The winners must be calculated first as the `TimeLimit` class [checks](https://github.com/Electroid/PGM/blob/master/core/src/main/java/tc/oc/pgm/timelimit/TimeLimit.java#L58-L61) to see if the countdown is at complete, however, the countdown is destroyed before this and a check for it returns null and then overall false to the check so the and `TeamVictoryCondition` can never be checked or succeed.

The winners should be calculated then the countdowns and schedulers ended like below.

```java
    calculateVictory();
    Set<Competitor> winners = this.competitors.getRank(0);
    getScheduler(MatchScope.RUNNING).cancel();
    getCountdown().cancelAll();
    callEvent(new MatchFinishEvent(this, winners));
```

After making the above change I discovered a further issue which again prevented the correct winner.

**Issue 2**: The priority of victory conditions are not accounted for

The various victory conditions previously had a priority that was used to decide which ones would be checked first, the priority still exists, however, these values are never checked or used for ordering.

The correct order/priority of these checks can be seen [here](https://github.com/Electroid/PGM/blob/7a2e9a4e4331387413528f515cb7f92645462ee6/core/src/main/java/tc/oc/pgm/api/party/VictoryCondition.java#L18), however, no order (and no completed check) is used when looping through the matches victory conditions, [see here](https://github.com/Electroid/PGM/blob/master/core/src/main/java/tc/oc/pgm/match/MatchImpl.java#L156-L164). The implementation in OCN PGM can be seen [here](https://github.com/OvercastNetwork/ProjectAres/blob/b883ef579938c49076379fa306592da847fc672f/PGM/src/main/java/tc/oc/pgm/victory/VictoryCalculator.java#L34-L36) where the conditions are checked for completion and for priority.

The first issue is an obvious and easy fix, however, the second would require deeper changes which I don't have the time or expertise to make.

**Comment by Electroid** [comment]
Thanks for writing this up! Fixed in 5f3efd80872d0a5d644dd06ae20503a88e7e26ad
