### ISSUE TITLE
Sending messages no longer renders the player name with a hover and click event

### ISSUE THREAD

**Issue by KingOfSquares** [Electroid/PGM#420]
When a message is sent through ChatDispatcher it used to render the player name with a hover and click event for teleporting to that player (if you have teleporting permissions). This is no longer done (my guess is it's because of 7a55789)

**Comment by Electroid** [comment]
This is a feature we have to give up in order for PGM to be compliant with other Bukkit plugins that listen to `AsyncPlayerChatEvent`. Unfortunately, this will not be brought back.
