### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by rafibaum** [Electroid/PGM#435]
There's no easy way to change settings right now other then `/setting` and `/toggle`, whose usability is terrible to say the least. This change would add options to change these settings inside a GUI menu which would be combined with the current `Observer Tools` menu to become a more general `Settings` menu. Each `SettingKey` value would also become associated with a `Material` which would be used to display the item in the menu. The text and lore would be handled more generally in a higher level `SettingMenuItem` class. Clicking on a setting in the menu would do the equivalent of `/toggle`.

**Comment by rafibaum** [comment]
Electroid approves in principle. `/settings` should trigger the GUI menu and with this change `/setting` and `/set` should be removed (rarely used and would conflict with tab-completing `/settings`), but `/toggle` should be left in place since people are aware of it.

**Comment by KingOfSquares** [comment]
Should close #217

**Comment by rafibaum** [comment]
Since this is a duplicate I'm going to go ahead and close this.
