### ISSUE TITLE
Allow maps to define arbitrary gamerules

### ISSUE THREAD

**Issue by RuedigerLP** [Electroid/PGM#449]
It would be rly useful to have the randomTickSpeed and keepInventory Gamerules configurable in the xml, and also to be 0/false on default. Some mapmaking servers mess with those numbers and then stuff doesn't drop and so on...

**Comment by TheMolkaPL** [comment]
You can change these by editing level.dat file in the map directory using NBTExplorer. But I'm pretty sure there was a module for gamerules in PGM already. Maybe in 1.9+?

**Comment by RuedigerLP** [comment]
Yes there is a module but it doesn't cover all gamerules.

**Comment by TheMolkaPL** [comment]
@Electroid you meant game rules, not game modes :p
