### ISSUE TITLE
You can no longer choose sendWarning playing a sound or not

### ISSUE THREAD

**Issue by KingOfSquares** [Electroid/PGM#450]
Making this issue because i'm not sure if its intended or not.

Many old methods use `void sendWarning(Component message, boolean audible)`
The new `sendWarning` always plays a sound.

Do i make it choosable?

**Comment by Electroid** [comment]
The idea is that all warnings give a little sound. Is there a reason to choose a sound or not?

**Comment by KingOfSquares** [comment]
Im just wondering how to convert old code. (e.g RegionMatchModule sends some warnings without sound)

**Comment by Electroid** [comment]
We can make them use sound then.
