### ISSUE TITLE
Entity templates

### ISSUE THREAD

**Issue by EricZeiberg** [Electroid/PGM#461]
After building the first iteration of the Spawner Module, it became clear that PGM does not yet have a robust way of parsing and building complex entities, such as entities wearing armor, holding items, with custom block drops. I propose a new way of handling entities in PGM, via this system / parser.  

Entities would be defined in the `<entities>` tag, and referenced elsewhere. The old syntax of `<entity>TYPE</entity>` would obviously still be supported. 

**Proposed syntax:** 
```
<entities>
<entity id="custom-zombie" health="20" type="Zombie">
  <drops>
     <drop chance="30">
        <item name="`6Golden Sword" material="gold sword"/>
    </drop>
  </drops>
  <equipment armor="armor-kit">
    <inhand>
      <item name="`6Golden Sword" material="gold sword"/>
    </inhand>
  </equipment> 
</entity>
</entities>
```

For `<equipment>` and `<inhand>`, these tags would only be supported by entities that can wear armor (Zombie, Skeleton, not sure who else?). Additionally, non-Living entities would only be supported via legacy syntax, as none of the above attributes apply to them. 

**Implementation:**
An additional parser type in `MapFactory` called `EntityParser` which will create a `PGMEntity`. This class will contain a `PGMEntityDefinition` and all the logic for creating the custom entity, spawning it and tracking it throughout its life cycle. `EntityParser` will also have legacy helper functions to maintain backwards compatibility. `EntityMapModule` will handle the main `<entities>` tag and `EntityMatchModule` will create the `PGMEntity` object.

My main concern is what to do about non-Living entities. Not supporting them is an easy route, but maybe there's another solution?

Feedback is appreciated!

**Comment by Pablete1234** [comment]
I have the feeling equipment should just be something that goes more along of what kits use, using a "slot" attribute instead of making sub-section for `inhand`

**Comment by EricZeiberg** [comment]
Can you give me an example?

**Comment by mitchts** [comment]
Alternative syntax
```xml
<kits>
    <kit id="custom-zombie-kit">
        <item material="stone sword"/>
        <item material="stick"/> <!-- ignored, no non-armor slots left -->
        <helmet material="iron helmet"/>
        <effect duration="30s">speed</effect>
        <health>40</health>
    </kit>
    <kit id="custom-zombie-drops">
        <any count="1..5" unique="false">
            <option weight="5">
                <item material="feather"/>
            </option>
            <option weight="1">
                <any>
                    <item material="iron"/>
                    <item material="stone sword"/>
                </any>
            </option>
        </any>
    </kit>
</kits>
<entities>
    <entitiy id="custom-zombie" kit="custom-zombie-kit" drop-kit="custom-zombie-drops"/>
</entities>
```

Drops example will not work due to lack of lootables module (ref: http://docs.oc.tc/modules/lootables#any).

**Comment by EricZeiberg** [comment]
That actually seems like a better idea, even without all the lootables stuff. Implementation wise, kits can only be applied to players however, and don't expose their content to outer classes. What's the best way to get around this?

**Comment by Electroid** [comment]
I would exclude drops from this, because I'd rather have it in the block drops module -- and somehow incorporate it. I would scope this, for now, to living entities with armor/weapon

**Comment by EricZeiberg** [comment]
After some more discussion, this feature will not be implemented at the moment. It requires a rather large refactor of the kits system, to account for non-player entities receiving kits, and will be explored after the 1.0 release. 

Closing until then.
