### ISSUE TITLE
CTF Helmet Vanishing Visual Bug

### ISSUE THREAD

**Issue by sharkskill** [Electroid/PGM#483]
**Description of bug** Currently, if you die after holding the flag, when you respawn nobody will be able to see your helmet apart from you. 
**Steps to reproduce** Start a CTF match, pick up a flag, /kill or die in another way, have another player look at you who was there when you died. 
**Extra information** When you take off the helmet yourself and put it back on other people can see it again. Sometimes when respawning you can see a helmet on your head after dying with the flag.
**Context** Currently this is an even bigger issue as it can make it much harder to see who is holding the flag for players on 1.7 as this is their only indicator for who has the flag. Because for some reason the particle beams used in PGM for marking flags do not show up for 1.7 players. Also 1.7 players can't see banners on players heads, but that's because banners are a 1.8 block.

**Comment by Pablete1234** [comment]
~~I'd make a separate issue for 1.7 stuff~~

**Comment by Pablete1234** [comment]
I'd make a separate issue for 1.7 stuff

**Comment by Pablete1234** [comment]
Reopened this to keep track of the helmet bug itself, the 1.7 issues have in the other issue have been fixed
