### ISSUE TITLE
Misleading setnext message

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#493]
So the message in admin chat that it sends when somebody setnexts a map, is quite misleading.
It makes it look like the person who set the map, is the *author* of the map being set.  It just shouldn't use the passive voice tbh

<img width="393" alt="Screen Shot 2020-05-16 at 7 08 08 PM" src="https://user-images.githubusercontent.com/54342797/82131968-d90c8e00-97a8-11ea-8fdd-638c31c9e7e7.png">

Doesn't it look like as though Zaquez made the map called Forge :p

It should just be "Zaquez set the next map to Forge"

**Comment by profbananaslug** [comment]
just when i thought map makers couldn't be bigger divas...

**Comment by applenick** [comment]
@Xerocoles 
 While it’s not a priority, I’ll include this change in a PR I’m making today/tomorrow to fix a `/vanish` bug. 🤷‍♂️
