### ISSUE TITLE
Remove Identity package

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#5]
Since nicks and flairs are now out-of-scope for PGM, both `Identity` and `Named` are not used enough to warrant its large amount of abstraction.

The source of truth for a player's display name, real name, and nick name should be the SportPaper APIs. No need to pass around and store an `Identity`. We should keep `PlayerComponent` but its rendering code can be changed to something along the lines of `Player#getDisplayName`.

**Comment by Pablete1234** [comment]
The issue here is that for nicked players, the rendering is different depending on who the viewer is, i'm not sure that `Player#getDisplayName` will give enough flexibility for 3rd party APIs to be able to integrate proper nicking.

**Comment by Electroid** [comment]
All other plugins use the display name system.. I'm not convinced we should be reinventing the wheel.

**Comment by AustinLMayes** [comment]
SportPaper also has viewer based name support (based on SportBukkit), so plugins can use that and if they need extra functionality they can add it themselves. 

The only additional APIs that PGM could expose is setting a different display name for chat, game messages (kills, objective stuff), and in tab

**Comment by Pablete1234** [comment]
If the server implementation has viewer based display name, that's all that's required for this, i agree.
