### ISSUE TITLE
Incorrect page display

### ISSUE THREAD

**Issue by ChemistryX** [Electroid/PGM#56]
![스크린샷 2019-11-06 오후 11 57 01](https://user-images.githubusercontent.com/10433434/68309667-1a352e80-00f2-11ea-8ceb-0b79dd17d81d.png)
The title says it has 7 pages of maps, but when I type `/maps 7` it says `Unknown page selected! 6 total pages`.
My server has 49 maps in total.

**Comment by Electroid** [comment]
Fixed https://github.com/Electroid/PGM/commit/0f27708b02034030cfa87a1cb76bb5faf7c2bf5f
