### ISSUE TITLE
Remove PGMUtil class

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#8]
`PGMUtil` was used during the refactor from PGM-with-backend to PGM-standalone. All of its logic can now be put into `PGM`.

**Comment by kei-kun41** [comment]
Hello,
Can I ask why you want to add the logic to PGM class ?
This class seems big enough to avoid adding the PGMUtils inside.

kei-kun41yt

**Comment by Electroid** [comment]
Done now.
