### ISSUE TITLE
Always picks the first spawn

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#84]
When there's more than one area a player can spawn in, it always picks the first.  (Or at least in every map I've seen so far)  At first I thought it was just FFAs, but then I realized it was also on the pre-loaded Warlock which has 2 spawns.

**Comment by TheMolkaPL** [comment]
Warlock has 1 spawn per team.

```xml
<spawns>
    <spawn kit="red-spawn" team="red" yaw="0">
        <cuboid min="40,6,-30" max="44,6,-34"/>
    </spawn>
    <spawn kit="blue-spawn" team="blue" yaw="180">
        <cuboid min="40,6,31" max="44,6,35"/>
    </spawn>
    <default yaw="90">
        <point>133.5,22,0.5</point>
    </default>
</spawns>
```

I need an example XML to reproduce it.

**Comment by Brottweiler** [comment]
I tried this on Interitus which has two spawns per team. I randomly respawn at either spawn when I die. This issue seems invalid, and you might have an outdated PGM version (you did in another issue).

**Comment by Xerocoles** [comment]
Oh I was dumb, I was thinking Warlock had 2 spawns in each corner.  But it's definitely happening in FFAs -- Maybe it's outdated code though, cause apparently lots of stratus stuff isn't up to date whether in-game or our mapdev server
