### ISSUE TITLE
You can't disable crafting certain items

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#86]
If you do something like the below image then you can still craft it.
<img width="256" alt="Screen Shot 2019-11-13 at 1 12 38 AM" src="https://user-images.githubusercontent.com/54342797/68737900-d2f7e380-05b2-11ea-911b-96ebce621638.png">

**Comment by Electroid** [comment]
Is it only certain items, or all of them?

**Comment by Xerocoles** [comment]
> Is it only certain items, or all of them?

I originally noticed it with boats, since we have commonly used that to avoid boat-glitching; I double-checked with sticks to make sure it wasn't just boats being weird since boats have undergone changes.  Since applying it to sticks doesn't work I would imagine it's all of them.

**Comment by TheMolkaPL** [comment]
I can't reproduce it on build e5b75aa19765747d9c10b227f7e2cd875a08f105 using

```xml
<crafting>
    <disable>stick</disable>
</crafting>
```

![image](https://user-images.githubusercontent.com/4578571/68773558-12aee180-062c-11ea-8c1a-c9dd3872501b.png)

![image](https://user-images.githubusercontent.com/4578571/68773591-20fcfd80-062c-11ea-8194-dcdc5b6ae48b.png)

What PGM version are you running? What's your client version?

**Comment by Electroid** [comment]
Seems you're running an outdated version of PGM, you should update!

**Comment by TheMolkaPL** [comment]
Should be somehow configurable then.
