### ISSUE TITLE
Lava keeps flowing when match is not running

### ISSUE THREAD

**Issue by TheMolkaPL** [Electroid/PGM#92]
1. break a core
2. wait until match ends
3. lava keeps flowing

**Comment by Brottweiler** [comment]
TNT also breaks blocks after game ends.

It worked like that on ocn too, but it didn't always work like that. I don't like when it broke, but the world used to stop being updated when the game ended.

**Comment by Pablete1234** [comment]
In very old-day PGM, world was frozen both at the start and end of the match. It was changed only to freeze before the match quite a long time ago tho. Cardinal did keep world freeze after ending the match tho, maybe that's what makes it feel more recent?

**Comment by Pugzy** [comment]
PGM proto 1.4.2 added a `pre-match-physics` attribute which defaulted to false described as..
> New pre-match-physics attribute for the terrain module to enable physics events before the match starts.

The logical solution (unless not possible due to server intensity) is to have interaction/physics off both before and after the match and use the aforementioned attribute is provided.

**Comment by KingOfSquares** [comment]
Solving this would likely include canceling all 
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockFromToEvent.html
and
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityExplodeEvent.html
after match end, any more events? I believe the rest of interaction is covered already.

**Comment by TheMolkaPL** [comment]
Just BlockTransformEvent :P

**Comment by KingOfSquares** [comment]
Would that stop flowing? Just seems like it stops player interaction with blocks.

**Comment by TheMolkaPL** [comment]
It should be called anytime a block changes its state.
