### ISSUE TITLE
Server restarts instantly after match end with no countdown, and sometimes ends mid match

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#95]
This is a hard one to reproduce since it happens when you least expect it. But I have two examples:

One time there was a game of BlockBlock, and I saw it was about to end. I forgot it was about to end, and suddely hear the end game wither death sound, and the server instantly restarted.

Yesterday, we had a 2v2 Blocks DTC game and both the enemy players were on their own side of the map. Suddenly, I hear the game end wither sound and I see "You Lost. Blue Team Wins" screen for a split second, before the server restarted. The game could impossibly have ended since no one leaked the core. I was defending the core while the entire enemy team was not even near it. I assume PGM just `/end`ed the game and it thought blue was in the lead, but it most definitely did end an incomplete game for some reason.

**Comment by Electroid** [comment]
Probably an issue with the queued Restart changes.

**Comment by Electroid** [comment]
https://github.com/Electroid/PGM/commit/100bea33cfc2306a5761e73288f3ccaae47edcdc
