### ISSUE TITLE
Respawning issues

### ISSUE THREAD

**Issue by CrazyisCreeps** [Electroid/PGM#98]
There's an issue with respawning that I only noticed started up with one of the recent commits. If you fall in the void, you appear to still taking damage after you die, causing you to die again (some how?) and get caught in a loop. Other people have reported that you get teleported all around the place while in the respawn screen.

**Comment by TheMolkaPL** [comment]
Duplicate of #89

**Comment by CrazyisCreeps** [comment]
Oh yea didn't even notice that one, thanks
